name: Verify translation parameters

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.12.0
        with:
          php: 8.0

      - name: Verify translation parameters
        run: php .github/workflows/verify-translation-parameters.php
